[[headers]]
for = "*"
[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"



[[headers]]
for = "/sitemap.xml"
[headers.values]
Content-type = "application/xml"



# Заголовки для мультиязычности
[[headers]]
for = "*/qr-code.png"
[headers.values]
Link = '''
</en/qr-code.png>; rel="alternate"; hreflang="en",
</ru/qr-code.png>; rel="alternate"; hreflang="ru",
</uk/qr-code.png>; rel="alternate"; hreflang="uk"
'''

[[headers]]
for = "*/vcard.vcf"
[headers.values]
Link = '''
</en/vcard.vcf>; rel="alternate"; hreflang="en",
</ru/vcard.vcf>; rel="alternate"; hreflang="ru",
</uk/vcard.vcf>; rel="alternate"; hreflang="uk"
'''

[[headers]]
for = "/"
[headers.values]
Content-Language = 'en'

[[headers]]
for = "/en/*"
[headers.values]
Content-Language = 'en'

[[headers]]
for = "/ru/*"
[headers.values]
Content-Language = 'ru'

[[headers]]
for = "/uk/*"
[headers.values]
Content-Language = 'uk'



# Перенаправления для мультиязычности
[[redirects]]
from = "/ru/"
to = "/"
status = 301
force = true
conditions = { Language = ["en"] }

[[redirects]]
from = "/uk/"
to = "/"
status = 301
force = true
conditions = { Language = ["en"] }


[[redirects]]
from = "/"
to = "/ru/"
status = 301
force = true
conditions = { Language = ["ru"] }

[[redirects]]
from = "/uk/"
to = "/ru/"
status = 301
force = true
conditions = { Language = ["ru"] }



[[redirects]]
from = "/"
to = "/uk/"
status = 301
force = true
conditions = { Language = ["uk"] }

[[redirects]]
from = "/ru/"
to = "/uk/"
status = 301
force = true
conditions = { Language = ["uk"] }
