[[headers]]
for = "/sitemap.xml"
[headers.values]
Content-type = "application/xml"

[[headers]]
for = "*/qrcode/*"
[headers.values]
Link = '''
</en/qrcode.png>; rel="alternate"; hreflang="en",
</ru/qrcode.png>; rel="alternate"; hreflang="ru",
</uk/qrcode.png>; rel="alternate"; hreflang="uk"
'''


[[headers]]
for = "/"
[headers.values]
Content-Language = 'en'

[[headers]]
for = "/en/*"
[headers.values]
Content-Language = 'en'

[[headers]]
for = "/ru/*"
[headers.values]
Content-Language = 'ru'

[[headers]]
for = "/uk/*"
[headers.values]
Content-Language = 'uk'




#
#[[redirects]]
#from = "/ru/"
#to = "/"
#status = 301
#force = true
#conditions = { Language = ["en"] }
#
#[[redirects]]
#from = "/uk/"
#to = "/"
#status = 301
#force = true
#conditions = { Language = ["en"] }
#
#
#[[redirects]]
#from = "/"
#to = "/ru/"
#status = 301
#force = true
#conditions = { Language = ["ru"] }
#
#[[redirects]]
#from = "/uk/"
#to = "/ru/"
#status = 301
#force = true
#conditions = { Language = ["ru"] }
#
#
#
#[[redirects]]
#from = "/"
#to = "/uk/"
#status = 301
#force = true
#conditions = { Language = ["uk"] }
#
#[[redirects]]
#from = "/ru/"
#to = "/uk/"
#status = 301
#force = true
#conditions = { Language = ["uk"] }
