[[headers]]
for = "/sitemap.xml"
[headers.values]
Content-type = "application/xml"

[[headers]]
for = "/images/qrcode-*"
[headers.values]
Link = '''
</qrcode-en.png>; rel="alternate"; hreflang="en",
</qrcode-ru.png>; rel="alternate"; hreflang="ru",
</qrcode-uk.png>; rel="alternate"; hreflang="uk"
'''


[[headers]]
for = "/images/qrcode-en.png"
[headers.values]
Content-Language = 'en'

[[headers]]
for = "/images/qrcode-ru.png"
[headers.values]
Content-Language = 'ru'

[[headers]]
for = "/images/qrcode-uk.png"
[headers.values]
Content-Language = 'uk'





[[redirects]]
from = "/ru/"
to = "/"
status = 301
force = true
conditions = { Language = ["en"] }

[[redirects]]
from = "/uk/"
to = "/"
status = 301
force = true
conditions = { Language = ["en"] }


[[redirects]]
from = "/"
to = "/ru/"
status = 301
force = true
conditions = { Language = ["ru"] }

[[redirects]]
from = "/uk/"
to = "/ru/"
status = 301
force = true
conditions = { Language = ["ru"] }



[[redirects]]
from = "/"
to = "/uk/"
status = 301
force = true
conditions = { Language = ["uk"] }

[[redirects]]
from = "/ru/"
to = "/uk/"
status = 301
force = true
conditions = { Language = ["uk"] }
